service: cutiro-api
app: cutiro-api
org: vin0uz

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3
  profile: cutiro
  timeout: 120

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  trigger:
    handler : trigger/handler.endpoint
  first_step:
    handler : step1/handler.start
  second_step:
    handler : step2/handler.start
  third_step:
    handler : step3/handler.start
  fourth_step:
    handler : step4/handler.start


stepFunctions:
  stateMachines:
    cleaning:
      ${file(serverless-cleaning.yml)}

plugins:
  - serverless-step-functions
  - serverless-python-requirements
  - serverless-dotenv-plugin
